mysite/mysite/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
)


urlpatterns += patterns('mysite.views',
	(r'^hello/$', 'hello'),
	(r'^time/$', 'current_datetime'),
	(r'^time/plus/(\d{1,2})/$', 'hours_ahead'),
    (r'^browser/$', 'display_browser'),
    (r'^meta/$', 'display_meta'),
    (r'^arhiv/(?P<year>\d{4})/(?P<month>\d{2})/$', 'show_archive_entries'),
    (r'^postevanka1/$','show_results', dict(template_name='temp1.html')),
    (r'^postevanka2/$','show_results', dict(template_name='temp2.html')),
)

urlpatterns += patterns('mysite.books.views',
    (r'^books/publishers/$', 'show_publishers'),
    (r'^search/$', 'search_book'),
)

mysite/books/models.py
from django.db import models

class Publisher(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=60)
    state_province = models.CharField(max_length=30)
    country = models.CharField(max_length=50)
    website = models.URLField()

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['name']

class Author(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=40)
    email = models.EmailField("e-mail", blank=True)

    def __unicode__(self):
        return u'%s %s' % (self.first_name, self.last_name)

class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField(Author)
    publisher = models.ForeignKey(Publisher)
    publication_date = models.DateField(blank=True, null=True)

    def __unicode__(self):
        return self.title

mysite/mysite/forms.py
from django import forms

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=20)
    email = forms.EmailField(required=False, label='Your e-mail address')
    message = forms.CharField(widget=forms.Textarea)

    def clean_message(self):
        message = self.cleaned_data['message']
        num_words = len(message)
        if num_words < 4:
            raise forms.ValidationError('More than 4 words, please!')
        return message

mysite/books/views.py
from django.shortcuts import render_to_response
from django.http import HttpResponse
from books.models import Publisher, Book

def show_publishers(request):
    publishers = Publisher.objects.all()
    return render_to_response("show_publishers.html",dict(publishers=publishers))

def search_book(request):
    error = None
    if 'q' in request.GET:
        q = request.GET['q']
        if not q:
            error = "Search string must not be empty!"
        elif len(q) > 20:
            error = "Search strings is too long!"
        else:
            books = Book.objects.filter(title__icontains=q)
            return render_to_response('search_results.html',dict(books=books, query=q))

    return render_to_response("search_form.html", dict(error=error))

mysite/mysite/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.core.mail import send_mail
from django.template.loader import get_template
from django.template import Context
from django.shortcuts import render_to_response
import datetime
from mysite.forms import ContactForm


def hello(request):
	return HttpResponse("Hello world!")


def current_datetime(request):
    now = datetime.datetime.now()
    # t = get_template('current_datetime.html')
    # html = t.render(Context({'datetime': now}))
    # return HttpResponse(html)
    return render_to_response("current_datetime.html", dict(datetime=now))

def hours_ahead(request, offset):
	try:
		offset = int(offset)
	except ValueError:
		raise Http404()
	dt = datetime.datetime.now() + datetime.timedelta(hours=offset)
	html = "<html><body>In %s hour(s), it will be %s.</body></html>" % (offset, dt)
	return HttpResponse(html)

def display_browser(request):
    browser = request.META.get("HTTP_USER_AGENT", "unknown")
    return HttpResponse("Your browser is %s" % browser)

def display_meta(request):
    meta = request.META.items()
    return render_to_response("display_meta.html", dict(meta=meta))

def search_form(request):
    return render_to_response('search_form.html')

def search(request):
    if 'q' in request.GET and request.GET["q"]:
        message = 'You searched for: %s. What is this?' % request.GET['q']
    else:
        message = 'Y U NO SEARCH for sth??'
    return HttpResponse(message)

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            send_mail(
                cd['subject'],
                cd['message'],
                cd.get('email', 'noreply@example.com'),
                ['siteowner@example.com'],
            )
            return HttpResponseRedirect('/contact/thanks/')
    else:
        form = ContactForm(
            initial='I love your site!'
        )
    return render_to_response('contact_form.html', {'form': form})

def show_archive_entries(request, month, year):
    return HttpResponse('Iskal si zapise iz leta %s in meseca %s' %( year, month))

def show_results(request, template_name):
    d = {v: v**2 for v in xrange(10)}
    return render_to_response(template_name, dict(d=d))

mysite/mysite/templates/contact_form.html
<!DOCTYPE html>
<html>
<head>
    <title>Contact us</title>
    <style>
        ul.errorlist {
            margin: 0;
            padding: 0;
        }
        .errorlist li {
            background-color: red;
            color: white;
            display: block;
            font-size: 10px;
            margin: 0 0 3px;
            padding: 4px 5px;
        }
    </style>
</head>
<body>
<h1>Contact us</h1>

{% if form.errors %}
    <p style="color: red;">
        Please correct the error{{ form.errors|pluralize }} below.
    </p>
{% endif %}

<form action="" method="post">
    <div class="field">
        {{ form.subject.errors }}
        <label for="id_subject">Subject:</label>
        {{ form.subject }}
    </div>
    <div class="field">
        {{ form.email.errors }}
        <label for="id_email">Your e-mail address:</label>
        {{ form.email }}
    </div>
    <div class="field">
        {{ form.message.errors }}
        <label for="id_message">Message:</label>
        {{ form.message }}
    </div>
    <input type="submit" value="Submit">
</form>
</body>
</html>

mysite/mysite/templates/current_datetime.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Trenutni čas</title>
</head>
<body>
    Trenutni čas je {{ datetime }}
</body>
</html>

mysite/mysite/templates/display_meta.html
<!DOCTYPE html>
<html>
<head>
    <title>Prikaz meta podatkov</title>
</head>
<body>
    <table>
        {% for item in meta %}
            <tr>
                <td>{{ item.0 }}</td>
                <td>{{ item.1 }}</td>
            </tr>
        {%  endfor %}
    </table>
</body>
</html>

mysite/mysite/templates/search_form.html
<!DOCTYPE html>
<html>
<head>
    <title>Search</title>
</head>
<body>
    {%  if error %}
    <p style="color:red;">{{ error }}</p>
    {%  endif %}
    <form action="" method="get">
        <input type="text" name="q">
        <input type="submit" value="Search">
    </form>
</body>
</html>

mysite/mysite/templates/search_results.html
<!DOCTYPE html>
<html>
<head>
    <title>Search results</title>
</head>
<body>
<p>You searched for: <strong>{{ query }}</strong></p>

{% if books %}
    <p>Found {{ books|length }} book{{ books|pluralize }}.</p>
    <ul>
        {% for book in books %}
            <li>{{ book.title }}</li>
        {% endfor %}
    </ul>
{% else %}
    <p>No books matched your search criteria.</p>
{% endif %}
</body>
</html>

mysite/mysite/templates/show_publishers.html
<!DOCTYPE html>
<html>
<head>
    <title>All publishers</title>
</head>
<body>

<table border="1">
    {% for publisher in publishers %}
        <tr>
            <td>{{ publisher.name }}</td>
            <td>{{ publisher.address }}</td>
            <td>{{ publisher.city }}</td>
            <td>{{ publisher.state_province }}</td>
            <td>{{ publisher.country }}</td>
            <td>{{ publisher.website }}</td>
        </tr>
    {% endfor %}
</table>
</body>
</html>

mysite/mysite/templates/temp1.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Prikaz postevanke na 2. način</title>
</head>
<body>
{% for n, n2 in d.items %}
<p>Kvadrat od {{ n }} je {{ n2 }}</p>
{%  endfor %}
</body>
</html>

mysite/mysite/templates/temp2.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Prikaz postevanke na 1. način</title>
</head>
<body>
<table border="1">
    <tr>
        <td>Stevilo</td>
        <td>Koren stevila</td>
    </tr>
    {% for n, n2 in d.items %}
    <tr>
        <td>{{ n }}</td>
        <td>{{ n2 }}</td>
    </tr>
    {%  endfor %}
</table>
</body>
</html>